extension LocalizedString on String {
  String tr(String languageCode) {
    if (languageCode == 'am') {
      return LocalisationService.translate(this);
    }
    return this;
  }
}

final class LocalisationService {
  LocalisationService();

  String languageCode = 'en';

  void setLanguage(String code) {
    languageCode = code;
  }

  static String translate(String key) {
    final trimmedKey = key.trim();
    if (_amharic.containsKey(trimmedKey)) {
      return _amharic[trimmedKey]!;
    }
    if (trimmedKey.startsWith('Extend your ') && trimmedKey.endsWith(' finger more.')) {
      final finger = trimmedKey.substring('Extend your '.length, trimmedKey.length - ' finger more.'.length);
      final amharicFinger = _amharic[finger] ?? finger;
      // ignore: unnecessary_brace_in_string_interps
      return '${amharicFinger}ዎን የበለጠ ይዘርጉ።';
    }
    if (trimmedKey.startsWith('Curl/bend your ') && trimmedKey.endsWith(' finger more.')) {
      final finger = trimmedKey.substring('Curl/bend your '.length, trimmedKey.length - ' finger more.'.length);
      final amharicFinger = _amharic[finger] ?? finger;
      // ignore: unnecessary_brace_in_string_interps
      return '${amharicFinger}ዎን የበለጠ ያጥፉ።';
    }
    return trimmedKey;
  }

  static const Map<String, String> _amharic = {
    // Nav bar / Main
    'Home': 'መነሻ',
    'Lessons': 'ትምህርቶች',
    'Dictionary': 'መዝገበ ቃላት',
    'AI Practice': 'የኤአይ ልምምድ',
    'Profile': 'መገለጫ',

    // Onboarding
    'Learn Ethiopian Sign Language for free': 'የኢትዮጵያ የምልክት ቋንቋን በነጻ ይማሩ',
    'Works offline - download lessons once': 'ከመስመር ውጭ ይሰራል - ትምህርቶችን አንዴ ያውርዱ',
    'Culturally relevant content': 'ባህላዊ ተገቢ ይዘት',
    'Get Started': 'ይጀምሩ',
    'Next': 'ቀጣይ',
    'Skip': 'ዝለል',

    // Auth screen
    'Welcome to': 'እንኳን ደህና መጡ ወደ',
    'Learn Ethiopian Sign Language at your own pace': 'የኢትዮጵያ የምልክት ቋንቋን በራስዎ ፍጥነት ይማሩ',
    'RESET DB': 'ዳታቤዝ አጽዳ',
    'Reset local data?': 'አካባቢያዊ መረጃዎችን ያጽዱ?',
    'This clears saved preferences on this device (login state, progress, etc.).': 'ይህ በዚህ መሣሪያ ላይ የተቀመጡ ቅንብሮችን ያጸዳል (የመግቢያ ሁኔታ፣ እድገት፣ ወዘተ)።',
    'Cancel': 'ሰርዝ',
    'Reset': 'ዳግም አስጀምር',
    'Local data cleared. Restart the app.': 'አካባቢያዊ መረጃዎች ጠርገዋል። መተግበሪያውን እንደገና ያስጀምሩ።',
    'Sign In': 'ግባ',
    'Email': 'ኢሜይል',
    'Password': 'የይለፍ ቃል',
    'Enter password': 'የይለፍ ቃል ያስገቡ',
    'Forgot password?': 'የይለፍ ቃል ረሱ?',
    'Don\'t have an account?': 'መለያ የለዎትም?',
    'Sign Up': 'ይመዝገቡ',
    'Create Account': 'መለያ ይፍጠሩ',
    'Full name': 'ሙሉ ስም',
    'Your name': 'ስምዎ',
    'Confirm password': 'የይለፍ ቃል ያረጋግጡ',
    'Sign Up & Start Learning': 'ይመዝገቡ እና መማር ይጀምሩ',
    'Back to sign in': 'ወደ መግቢያ ይመለሱ',
    'Forgot Password': 'የይለፍ ቃልዎን ረሱ',
    'Send Reset Code': 'የይለፍ ቃል ዳግም ማስጀመሪያ ኮድ ላክ',
    'Reset Password': 'የይለፍ ቃል ዳግም አስጀምር',
    'Reset code': 'ኮድ',
    'Enter code': 'ኮድ ያስገቡ',
    'New password': 'አዲስ የይለፍ ቃል',
    'Confirm new password': 'አዲስ የይለፍ ቃል ያረጋግጡ',
    'Please enter your email address': 'እባክዎ የኢሜይል አድራሻዎን ያስገቡ',
    'Please enter a valid email address': 'እባክዎ ትክክለኛ የኢሜይል አድራሻ ያስገቡ',
    'Please enter your password': 'እባክዎ የይለፍ ቃልዎን ያስገቡ',
    'Password must be at least 6 characters': 'የይለፍ ቃል ቢያንስ 6 ቁምፊዎች መሆን አለበት',
    'Please enter your full name': 'እባክዎ ሙሉ ስምዎን ያስገቡ',
    'Name must be at least 2 characters': 'ስም ቢያንስ 2 ቁምፊዎች መሆን አለበት',
    'Please enter a password': 'እባክዎ የይለፍ ቃል ያስገቡ',
    'Please confirm your password': 'እባክዎ የይለፍ ቃልዎን ያረጋግጡ',
    'Passwords do not match': 'የይለፍ ቃላቱ አይዛመዱም',
    'Could not load new account.': 'አዲሱን መለያ መጫን አልተቻለም።',

    // Drawer
    'HELP & SUPPORT': 'እርዳታ እና ድጋፍ',
    'Help': 'እርዳታ',
    'How to use': 'እንዴት መጠቀም እንደሚቻል',
    'Contact ENAD': 'ኢ.ብ.ማ.ማ.ን ያግኙ',
    'ABOUT': 'ስለ መተግበሪያው',
    'App Info': 'የመተግበሪያ መረጃ',
    'Version': 'ስሪት',
    'Credits': 'ክሬዲቶች (ምስጋና)',
    'Settings': 'ቅንብሮች',
    'ETHIOPIAN NATIONAL ASSOCIATION OF THE DEAF': 'የኢትዮጵያ ብሔራዊ የማኅበረሰበ ደንቆሮዎች ማኅበር',
    'Settings coming soon': 'ቅንብሮች በቅርቡ ይመጣሉ',

    // Home
    'Hello! 👋': 'ሰላም! 👋',
    'Learn Ethiopian Sign\nLanguage!': 'የኢትዮጵያ የምልክት\nቋንቋ ይማሩ!',
    'Continue Learning': 'መማርዎን ይቀጥሉ',
    'Continue Your Journey': 'ጉዞዎን ይቀጥሉ',
    'Resume Now': 'አሁን ይቀጥሉ',
    'Quick Categories': 'ፈጣን ምድቦች',
    'View All': 'ሁሉንም ይመልከቱ',
    'All lessons complete!': 'ሁሉንም ትምህርቶች አጠናቀዋል!',
    'Review categories or take a quiz': 'ምድቦችን ይከልሱ ወይም ፈተና ይውሰዱ',
    'Practice Quiz of the Day': 'የዕለቱ የልምምድ ፈተና',
    'Test Your Daily Goals!': 'የዕለት ተዕለት ግቦችዎን ይፈትሹ!',
    'Ethiopian Culture': 'የኢትዮጵያ ባህል',
    'CULTURAL SIGN': 'ባህላዊ ምልክት',
    'Cultural signs will appear here when an admin adds them with a home card image.': 'አስተዳዳሪው የፊት ገጽ ምስል ያላቸውን ባህላዊ ምልክቶች ሲያክሉ እዚህ ይታያሉ።',
    'No lesson category selected yet.': 'ምንም የትምህርት ምድብ አልተመረጠም።',

    // Lessons Screen
    'Choose a category to start learning': 'ለመማር ምድብ ይምረጡ',
    'YOUR ACTIVITY': 'የእርስዎ እንቅስቃሴ',
    'Learning Progress': 'የመማር ሂደት',
    'of': 'ከ',
    'lessons completed': 'ትምህርቶች ተጠናቀዋል',
    'done': 'ተጠናቋል',
    'No signs found': 'ምንም ምልክቶች አልተገኙም',

    // Lesson Detail
    'completed': 'ተጠናቋል',
    'lessons': 'ትምህርቶች',
    'Start Learning': 'መማር ይጀምሩ',

    // Video detail screen
    'No video URL for this sign yet.': 'ለዚህ ምልክት ቪዲዮ አልተዘጋጀም።',
    'Video saved for offline playback.': 'ቪዲዮው ከኢንተርኔት ውጪ እንዲሠራ ተቀምጧል።',
    'Download failed': 'ማውረድ አልተሳካም',
    'Practice with camera': 'በካሜራ ይለማመዱ',
    'Take a quiz': 'ፈተና ይውሰዱ',
    'Download Video': 'ቪዲዮ አውርድ',
    'Offline Video': 'ከመስመር ውጭ ቪዲዮ',
    'Delete': 'ሰርዝ',
    'Learned': 'ተምሬአለሁ',
    'Cultural Note': 'ባህላዊ ማስታወሻ',
    'Mark as Learned': 'እንደተማረ ምልክት አድርግ',
    'Preparing sign video…': 'ምልክት ቪዲዮ በመዘጋጀት ላይ ነው…',
    'Download Video for offline playback': 'ከመስመር ውጭ ለማጫወት ቪዲዮውን ያውርዱ',
    'Delete local video file': 'የተቀመጠውን ቪዲዮ ሰርዝ',
    'Practice this sign using your camera': 'ካሜራዎን በመጠቀም ይህንን ምልክት ይለማመዱ',
    'Take a quiz on this category': 'በዚህ ምድብ ላይ ፈተና ይውሰዱ',

    // Quiz
    'Quiz': 'ፈተና',
    'Question': 'ጥያቄ',
    'What is the sign for': 'የዚህ ቃል ምልክት ምንድነው:',
    'Quiz Complete': 'ፈተናው ተጠናቋል',
    'Your Score': 'ውጤትዎ',
    'Back to home': 'ወደ መነሻ ገጽ',
    'Well done!': 'በጣም ጎበዝ!',
    'Keep practicing!': 'ልምምድዎን ይቀጥሉ!',

    // AI Practice
    'Practice Sign': 'ምልክቱን ይለማመዱ',
    'Camera access is required to practice sign language gestures.': 'የምልክት ቋንቋ እንቅስቃሴዎችን ለመለማመድ የካሜራ ፈቃድ ያስፈልጋል።',
    'Gesture recognized': 'ምልክቱ ተለይቷል',
    'Try again': 'እንደገና ይሞክሩ',
    'Perfect match!': 'ፍጹም ተዛማጅ!',
    'Close': 'ዝጋ',
    'Sign detected:': 'የተገኘው ምልክት:',
    'Show Camera': 'ካሜራ አሳይ',

    // Profile
    'Save Changes': 'ለውጦችን አስቀምጥ',
    'New Password': 'አዲስ የይለፍ ቃል',
    'Current Password': 'የአሁኑ የይለፍ ቃል',
    'Profile saved successfully': 'መገለጫዎ በተሳካ ሁኔታ ተቀምጧል',
    'Log Out': 'ውጣ',
    'Change Profile Picture': 'የመገለጫ ምስል ቀይር',
    'Manage your account preferences': 'የመለያ ቅንብሮችዎን ያስተዳድሩ',
    'Edit Profile': 'መገለጫ ያርትዑ',
    'Update your name and password': 'ስምዎን እና የይለፍ ቃልዎን ያዘምኑ',
    'Admin Panel': 'የአስተዳዳሪ ፓነል',
    'Manage lessons, users, and content': 'ምድቦችን፣ ትምህርቶችን እና ተጠቃሚዎችን ያስተዳድሩ',
    'Account Settings': 'የመለያ ቅንብሮች',
    'STREAK': 'ቀናት',
    'SIGNS LEARNED': 'የተማሯቸው ምልክቶች',
    'PRACTICE HOURS': 'የልምምድ ሰዓታት',

    // Admin Dashboard
    'Admin Dashboard': 'የአስተዳዳሪ ሰሌዳ',
    'Manage Categories': 'ምድቦችን ያስተዳድሩ',
    'Manage Lessons': 'ትምህርቶችን ያስተዳድሩ',
    'Manage Users': 'ተጠቃሚዎችን ያስተዳድሩ',
    'Total Categories': 'አጠቃላይ ምድቦች',
    'Total Lessons': 'አጠቃላይ ትምህርቶች',
    'Total Users': 'አጠቃላይ ተጠቃሚዎች',
    'Manage categories and their sign videos': 'ምድቦችን እና የምልክት ቪዲዮዎችን ያስተዳድሩ',

    // Admin Categories
    'Categories': 'ምድቦች',
    'Add Category': 'ምድብ ጨምር',
    'Edit Category': 'ምድብ አርትዕ',
    'Delete Category': 'ምድብ ሰርዝ',
    'Edit Sign': 'ምልክት አርትዕ',
    'Delete Sign': 'ምልክት ሰርዝ',
    'No signs in this category yet.': 'እስካሁን በዚህ ምድብ ውስጥ ምንም ምልክቶች የሉም።',
    'Are you sure you want to delete this category? All signs under it will lose their category association.': 'እርግጠኛ ነዎት ይህንን ምድብ መሰረዝ ይፈልጋሉ? በእሱ ስር ያሉ ሁሉም ምልክቶች የምድብ ትስስራቸውን ያጣሉ።',
    'Add Sign': 'ምልክት ጨምር',
    'Category Form': 'የምድብ ፎርም',
    'Title (English)': 'ርዕስ (እንግሊዝኛ)',
    'Title (Amharic)': 'ርዕስ (አማርኛ)',
    'Description': 'መግለጫ',
    'Icon (Emoji)': 'አይኮን (ኢሞጂ)',
    'Color (Hex)': 'ቀለም (ሄክስ)',
    'Please enter English title': 'እባክዎ የእንግሊዝኛ ርዕስ ያስገቡ',
    'Please enter Amharic title': 'እባክዎ የአማርኛ ርዕስ ያስገቡ',
    'Please enter description': 'እባክዎ መግለጫ ያስገቡ',
    'Please enter icon emoji': 'እባክዎ አይኮን ያስገቡ',
    'Save': 'አስቀምጥ',
    'Category saved successfully': 'ምድብ በተሳካ ሁኔታ ተቀምጧል',

    // Admin Lessons
    'Add Lesson': 'ትምህርት ጨምር',
    'Edit Lesson': 'ትምህርት አርትዕ',
    'Delete Lesson': 'ትምህርት ሰርዝ',
    'Are you sure you want to delete this sign?': 'እርግጠኛ ነዎት ይህንን ምልክት መሰረዝ ይፈልጋሉ?',
    'Lesson Form': 'የትምህርት ፎርም',
    'Sign Name (English)': 'የምልክቱ ስም (እንግሊዝኛ)',
    'Sign Name (Amharic)': 'የምልክቱ ስም (አማርኛ)',
    'Thumbnail (Emoji)': 'ምስል (ኢሞጂ)',
    'Video URL / File ID (Google Drive)': 'የቪዲዮ ሊንክ / ፋይል መለያ (ጎግል ድራይቭ)',
    'Cultural Note (Optional)': 'ባህላዊ ማስታወሻ (አማራጭ)',
    'Show on Culture Card (Home Page)': 'በባህላዊ ካርድ ላይ አሳይ (መነሻ ገጽ)',
    'Local Image Path for Culture Card': 'በባህላዊ ካርድ ላይ የሚሆን ምስል',
    'Please enter English sign name': 'እባክዎ የእንግሊዝኛ ምልክት ስም ያስገቡ',
    'Please enter Amharic sign name': 'እባክዎ የአማርኛ ምልክት ስም ያስገቡ',
    'Please enter thumbnail emoji': 'እባክዎ ምስል ያስገቡ',
    'Please select a category': 'እባክዎ ምድብ ይምረጡ',
    'Lesson saved successfully': 'ትምህርት በተሳካ ሁኔታ ተቀምጧል',

    // Admin Users
    'Users': 'ተጠቃሚዎች',
    'Admin': 'አስተዳዳሪ',
    'Learner': 'ተማሪ',
    'Toggle Admin Role': 'የአስተዳዳሪነት ሚና ቀይር',
    'User status updated': 'የተጠቃሚ ሁኔታ ተዘምኗል',
    'Delete User': 'ተጠቃሚ ሰርዝ',
    'Are you sure you want to delete this user?': 'እርግጠኛ ነዎት ይህንን ተጠቃሚ መሰረዝ ይፈልጋሉ?',
    'No users registered yet.': 'እስካሁን ምንም ተጠቃሚ አልተመዘገበም።',
    'Signs': 'ምልክቶች',
    'Streak': 'ተከታታይ ቀናት',
    'Practiced': 'ልምምድ',
    'Error': 'ስህተት',
    'User': 'ተጠቃሚ',

    // Admin AI Practice Gesture templates
    'AI Hand Gestures': 'የኤአይ እጅ ምልክቶች',
    'Manage trained sign hand shapes and coordinate templates': 'የሰለጠኑ ምልክቶችን የእጅ ቅርጾች እና መጋጠሚያዎችን ያስተዳድሩ',
    'Train New Sign': 'አዲስ ምልክት አሰልጥን',
    'No trained sign templates yet.\nTap "Train New Sign" to record hand shapes.': 'እስካሁን የሰለጠኑ የምልክት መጋጠሚያዎች የሉም።\nየእጅ ቅርጾችን ለመመዝገብ "አዲስ ምልክት አሰልጥን" የሚለውን ይንኩ።',
    'Coordinates': 'መጋጠሚያዎች',
    'Unknown Category': 'ያልታወቀ ምድብ',
    'Delete template?': 'መጋጠሚያዎች ይሰረዙ?',
    'Train Gesture': 'የእጅ ምልክት አሰልጥን',
    'Select Sign to Train': 'ለማሰልጠን ምልክት ይምረጡ',
    'Please select a sign': 'እባክዎ ምልክት ይምረጡ',
    'No hand detected in the frame. Try again.': 'በካሜራው እይታ ውስጥ ምንም እጅ አልተገኘም። እንደገና ይሞክሩ።',
    'Hand landmarks captured successfully!': 'የእጅ ምልክቶች በተሳካ ሁኔታ ተመዝግበዋል!',
    'Please select a sign to train.': 'እባክዎ ለማሰልጠን ምልክት ይምረጡ።',
    'Sign gesture trained successfully!': 'የእጅ ምልክቱ በተሳካ ሁኔታ ሰልጥኗል!',
    'Landmark Coordinates (63 values)': 'የመጋጠሚያ መረጃዎች (63 እሴቶች)',
    'Provide comma-separated coordinates manually or record via camera above.': 'የመጋጠሚያ እሴቶችን በኮማ በመለየት እዚህ ያስገቡ ወይም ከላይ ካለው ካሜራ ላይ ይቅረጹ።',
    'Capture Pose': 'የእጅ ምልክት ቅረጽ',



    // Drawer info pages
    'Welcome to Miliketapp': 'እንኳን ወደ ሚሊከት መተግበሪያ በደህና መጡ',
    'Miliketapp helps you learn Ethiopian Sign Language (EthSL) through video lessons, quizzes, a sign dictionary, and optional AI hand-practice.': 'ሚሊከት መተግበሪያ በቪዲዮ ትምህርቶች፣ ጥያቄዎች፣ የምልክት መዝገበ ቃላት እና በኤአይ እገዛ የምልክት ልምምዶች የኢትዮጵያ የምልክት ቋንቋን (EthSL) ለመማር ያግዝዎታል።',
    'Frequently asked questions': 'ተደጋግመው የሚጠየቁ ጥያቄዎች',
    'Video will not play': 'ቪዲዮው አልጫወት ካለ',
    'Sign videos are hosted on Google Drive. Use a stable internet connection, wait for “Preparing sign video…”, or tap Download for offline on the lesson screen. If a sign still fails, the file may need to be shared publicly by your teacher.': 'የምልክት ቪዲዮዎች በጎግል ድራይቭ ላይ የተስተናገዱ ናቸው። የተረጋጋ የኢንተርኔት ግንኙነት ይጠቀሙ፣ “ምልክት ቪዲዮ በመዘጋጀት ላይ ነው…” እስኪል ይጠብቁ፣ ወይም በትምህርት ገጹ ላይ ከመስመር ውጭ ለማጫወት “አውርድ” የሚለውን ይጫኑ። ቪዲዮው አሁንም አልጫወት ካለ አስተማሪዎ ቪዲዮውን ለሁሉም ክፍት ማድረጋቸውን ያረጋግጡ።',
    'Progress and completed lessons': 'የመማር ሂደት እና ያለቁ ትምህርቶች',
    'Your progress is saved on this device. Watch most of a lesson video or pass a quiz to mark a sign as learned. Check the Lessons screen for category progress bars.': 'የእርስዎ ሂደት በዚህ መሣሪያ ላይ ተቀምጧል። አንድን ምልክት እንደተማረ ምልክት ለማድረግ አብዛኛውን የቪዲዮ ትምህርት ይመልከቱ ወይም ፈተናውን ይለፉ። የምድብ ሂደቶችን ለመከታተል በትምህርቶች ገጽ ላይ ያሉትን የሂደት ጠቋሚዎች ይመልከቱ።',
    'Open Dictionary from the bottom bar to search signs in English or Amharic and jump straight to the lesson video.': 'በእንግሊዝኛ ወይም በአማርኛ ምልክቶችን ለመፈለግ እና በቀጥታ ወደ ትምህርቱ ቪዲዮ ለመሄድ ከታችኛው አሞሌ መዝገበ ቃላትን ይክፈቱ።',
    'AI practice': 'የኤአይ ልምምድ',
    'AI practice uses your camera to compare hand shapes to a template. Use good lighting, keep your hand in frame, and hold the sign steady.': 'የኤአይ ልምምድ የእጅዎን ቅርጾች ከምሳሌው ጋር ለማነፃፀር ካሜራዎን ይጠቀማል። ጥሩ ብርሃን ይጠቀሙ፣ እጅዎን በካሜራው ክፈፍ ውስጥ ያድርጉ፣ እና እጅዎን ሳያንቀሳቅሱ ያቆዩ።',
    'Account and language': 'መለያ እና ቋንቋ',
    'Sign in to sync progress when available. Change display language (English / Amharic) from Profile in the drawer or bottom navigation.': 'እድገትዎን ለማመሳሰል መለያ ይግቡ። የዕይታ ቋንቋውን (እንግሊዝኛ / አማርኛ) በጎን ምናሌው ወይም በታችኛው አሞሌ ላይ ካለው መገለጫ ውስጥ ይቀይሩ።',
    'Follow these steps to get the most from Miliketapp. You can learn at your own pace—repeat videos as often as you need.': 'ከሚሊከት መተግበሪያ ምርጡን ጥቅም ለማግኘት እነዚህን ደረጃዎች ይከተሉ። በራስዎ ፍጥነት መማር ይችላሉ — ቪዲዮዎችን እንደ አስፈላጊነቱ ደጋግመው ይመልከቱ።',
    '1. Start on Home': '1. በመነሻ ገጽ ይጀምሩ',
    'See your streak, signs learned, and quick links to categories.': 'የተማሯቸውን ምልክቶች፣ ተከታታይ ቀናትዎን እና የምድቦች ፈጣን አገናኞችን ይመልከቱ።',
    'Tap a category card to open lessons for that topic.': 'የአንድን ርዕስ ትምህርቶች ለመክፈት የምድብ ካርዱን ይንኩ።',
    '2. Learn a sign': '2. ምልክቶችን ይማሩ',
    'Open Lessons, pick a category (Greetings, Family, Food, etc.).': 'ትምህርቶችን ይክፈቱ፣ ምድብ ይምረጡ (ሰላምታ፣ ቤተሰብ፣ ምግብ፣ ወዘተ)።',
    'Tap a sign to watch the EthSL video with mirror and speed controls.': 'የ EthSL ቪዲዮውን በመስታወት እይታ እና በፍጥነት መቆጣጠሪያዎች ለመመልከት አንድን ምልክት ይንኩ።',
    'Use Download for offline if you will study without internet.': 'ያለ ኢንተርኔት የሚያጠኑ ከሆነ ከመስመር ውጭ አውርድን ይጠቀሙ።',
    '3. Practice': '3. ይለማመዱ',
    'Tap Practice Quiz after watching to test recognition.': 'ያዩትን የምልክት እውቀት ለመፈተሽ ከቪዲዮው በኃላ “ፈተና ይውሰዱ” የሚለውን ይንኩ።',
    'Try AI Practice on supported signs for real-time hand feedback.': 'በሚደገፉ ምልክቶች ላይ የእጅ እንቅስቃሴዎችዎን ለመለማመድ የኤአይ ልምምድን ይሞክሩ።',
    '4. Review': '4. ይከልሱ',
    'Use Dictionary to find a sign by name anytime.': 'በማንኛውም ጊዜ አንድን ምልክት በስም ለመፈለግ መዝገበ ቃላትን ይጠቀሙ።',
    'Track completion on each category card (e.g. 3/19).': 'በእያንዳንዱ ምድብ ካርድ ላይ ምን ያህል እንደጨረሱ ይከታተሉ (ለምሳሌ 3/19)።',
    'Tips': 'ጠቃሚ ምክሮች',
    'Mirror mode flips the video—helpful when copying the signer.': 'የመስታወት እይታ (Mirror mode) ቪዲዮውን ይገለብጠዋል — ምልክቶችን ከቪዲዮው ላይ ለመቅዳት ይረዳል።',
    'Slow playback (0.5×–0.75×) helps with new or fast movements.': 'ዘገምተኛ ማጫወት (0.5×–0.75×) አዳዲስ ወይም ፈጣን እንቅስቃሴዎችን ለመለየት ይረዳል።',
    'Use Previous / Next on the video screen to move through a category.': 'በአንድ ምድብ ውስጥ ለመዘዋወር በቪዲዮው ማያ ገጽ ላይ የቀደመውን / የሚቀጥለውን ይጠቀሙ።',
    'Ethiopian National Association of the Deaf (ENAD)': 'የኢትዮጵያ ብሔራዊ የማኅበረሰበ ደንቆሮዎች ማኅበር (ኢ.ብ.ማ.ማ)',
    'ENAD advocates for Deaf rights, Ethiopian Sign Language, and accessible education across Ethiopia. Miliketapp is developed in support of EthSL learning.': 'ኢ.ብ.ማ.ማ በመላው ኢትዮጵያ ለደንቆሮዎች መብት፣ ለኢትዮጵያ የምልክት ቋንቋ እና ተደራሽ ትምህርት ይሟገታል። ሚሊከት መተግበሪያ የተገነባው የኢትዮጵያ የምልክት ቋንቋን ለመደገፍ ነው።',
    'Get in touch': 'ያግኙን',
    'ENAD — Addis Ababa': 'ኢ.ብ.ማ.ማ — አዲስ አበባ',
    'Visit or write to ENAD for programs, interpreter services, community events, and partnership opportunities related to Deaf education.': 'ለፕሮግራሞች፣ አስተርጓሚ አገልግሎቶች፣ ለማህበረሰብ ዝግጅቶች እና ከደንቆሮዎች ትምህርት ጋር በተያያዙ የሽርክና እድሎች ለማግኘት ወደ ማኅበሩ ይጎብኙ ወይም ይጻፉ።',
    'For technical issues with Miliketapp (videos, login, crashes), contact your school or project coordinator first. Include your device model and a screenshot of any error message.': 'ከሚሊከት መተግበሪያ ጋር በተያያዙ ቴክኒካዊ ችግሮች (ቪዲዮዎች፣ መግቢያ፣ መቆራረጥ) መጀመሪያ ትምህርት ቤትዎን ወይም የፕሮጀክት አስተባባሪዎን ያነጋግሩ። የመሳሪያዎን ሞዴል እና የማንኛውም የስህተት መልዕክት ፎቶ ያያይዙ።',
    'Learning feedback': 'የትምህርት አስተያየት',
    'If a sign video is wrong or missing, tell your instructor so the correct Google Drive link can be added to the lesson.': 'አንድ የምልክት ቪዲዮ የተሳሳተ ወይም የሌለ ከሆነ ትክክለኛው የጎግል ድራይቭ ሊንክ በትምህርቱ ላይ እንዲታከል ለአስተማሪዎ ይንገሩ።',
    'Purpose': 'ዓላማ',
    'Miliketapp is a mobile learning companion for Ethiopian Sign Language. It combines structured lessons, visual quizzes, a searchable dictionary, and practice tools designed for Deaf learners, hearing family members, teachers, and interpreters.': 'ሚሊከት መተግበሪያ የኢትዮጵያ የምልክት ቋንቋ መማሪያ የሞባይል ረዳት ነው። ለደንቆሮ ተማሪዎች፣ ለቤተሰብ አባላት፣ ለመምህራን እና ለአስተርጓሚዎች የተዘጋጁ ትምህርቶችን፣ ምስላዊ ጥያቄዎችን፣ ሊፈለግ የሚችል መዝገበ ቃላት እና የመለማመጃ መሳሪያዎችን ያጣምራል።',
    'Release 1.0.0 — local-first storage, video lessons, quizzes, and AI practice.': 'ስሪት 1.0.0 — የአካባቢ ማከማቻ፣ የቪዲዮ ትምህርቶች፣ ጥያቄዎች እና የኤአይ ልምምድ።',
    'Privacy': 'ግላዊነት',
    'Lesson progress and account details are stored on your device. Sign-in uses a local account database; do not share your password.': 'የትምህርት ሂደት እና የመለያ ዝርዝሮች በስልክዎ ላይ ተቀምጠዋል። መግቢያ የአካባቢያዊ መለያ የውሂብ ጎታ ይጠቀማል፤ የይለፍ ቃልዎን ለማንም አያካፍሉ።',
    'Content': 'ይዘት',
    'Sign videos and lesson lists are curated for EthSL. Categories include greetings, family, food, shopping, emergency phrases, and numbers.': 'የምልክት ቪዲዮዎች እና የትምህርት ዝርዝሮች ለ EthSL የተዘጋጁ ናቸው። ምድቦች ሰላምታን፣ ቤተሰብን፣ ምግብን፣ ግብይትን፣ የአደጋ ጊዜ ሀረጎችን እና ቁጥሮችን ያካትታሉ።',
    'Miliketapp is made possible through collaboration with the Deaf community, educators, and technology volunteers.': 'ሚሊከት መተግበሪያ ከደንቆሮው ማህበረሰብ፣ ከባለሙያዎች እና ከቴክኖሎጂ በጎ ፈቃደኞች ጋር በመተባበር የተዘጋጀ ነው።',
    'Organizations': 'ድርጅቶች',
    'Ethiopian National Association of the Deaf (ENAD) — community guidance.': 'የኢትዮጵያ ብሔራዊ የማኅበረሰበ ደንቆሮዎች ማኅበር (ኢ.ብ.ማ.ማ) — የማህበረሰብ አመራር።',
    'Sign content': 'የምልክት ይዘት',
    'EthSL signers and teachers who record and review lesson videos.': 'የትምህርት ቪዲዮዎችን የቀረጹ እና የገመገሙ የ EthSL ምልክት ሰጪዎች እና መምህራን።',
    'Lesson authors who prepare English and Amharic labels.': 'የእንግሊዝኛ እና የአማርኛ ስያሜዎችን ያዘጋጁ የትምህርት አዘጋጆች።',
    'Technology': 'ቴክኖሎጂ',
    'Built with Flutter for Android (and supported platforms).': 'በፍሉተር (Flutter) ለአንድሮይድ የተገነባ።',
    'On-device AI hand templates powered by TensorFlow Lite.': 'በስልክ ላይ የሚሰራ የኤአይ እጅ ቅርጽ መፈተሻ በቴንሰርፍሎው ላይት የተጎላበተ።',
    'Video hosting via Google Drive with offline download support.': 'የቪዲዮ ማስተናገጃ በጎግል ድራይቭ ከመስመር ውጭ ማውረድ ድጋፍ ጋር።',
    'Acknowledgements': 'ምስጋና',
    'Thank you to every learner who provides feedback to improve lessons and accessibility. Special thanks to families and schools promoting Ethiopian Sign Language literacy.': 'ትምህርቶችን እና ተደራሽነትን ለማሻሻል አስተያየት ለሚሰጡ ተማሪዎች ሁሉ እናመሰግናለን። የኢትዮጵያ የምልክት ቋንቋ ማንበብ እና መጻፍን ለሚያስተዋውቁ ቤተሰቦች እና ትምህርት ቤቶች ልዩ ምስጋና እናቀርባለን።',
    // Categories and general words from Video Screen
    'Greetings': 'ሰላምታ',
    'Family': 'ቤተሰብ',
    'Food': 'ምግብ',
    'Shopping': 'ግብይት',
    'Emergency': 'አደጋ ጊዜ',
    'Numbers': 'ቁጥሮች',
    'Lesson': 'ትምህርት',
    'Previous': 'ቀዳሚ',
    'Practice Quiz': 'የልምምድ ፈተና',
    'Sign learned! +1 to your\nprogress': 'ምልክቱ ተምረዋል! +1 ወደ እድገትዎ',
    'Cultural context': 'ባህላዊ ይዘት',
    'Downloaded (Offline)': 'ወርዷል (ከመስመር ውጭ)',
    'Download for offline': 'ከመስመር ውጭ ያውርዱ',
    // Quiz Screen
    'Complete': 'ተጠናቋል',
    'Ethiopian Sign Language': 'የኢትዮጵያ የምልክት ቋንቋ',
    'What sign is being shown?': 'የሚታየው ምልክት ምንድነው?',
    'Watch the video carefully and select the\ncorrect meaning of the gesture performed.': 'ቪዲዮውን በጥንቃቄ ይመልከቱ እና የእጅ ምልክቱን ትክክለኛ ትርጉም ይምረጡ።',
    'Next Question': 'ቀጣይ ጥያቄ',
    // AI Practice Screen & Model Feedback
    'Initializing hand tracker...': 'የእጅ መከታተያውን በመጀመር ላይ...',
    'Hold your hand in camera view to practice.': 'ለመለማመድ እጅዎን በካሜራው እይታ ውስጥ ያቆዩ።',
    'Practice sign is not trained yet.': 'የልምምድ ምልክቱ ገና አልሰለጠነም።',
    'Please train this sign externally and save its coordinate template into the database.': 'እባክዎን ይህንን ምልክት በውጭ አሰልጥነው እና የተቀናጀውን ሞዴል በዳታቤዝ ውስጥ ያስቀምጡ።',
    'Analysing... Keep your hand within the frame.': 'በመተንተን ላይ... እጅዎን በካሜራው ክፈፍ ውስጥ ያድርጉ።',
    'Analyzing... Hold your pose steady.': 'በመተንተን ላይ... ምልክቱን ሳያንቀሳቅሱ ያቆዩ።',
    'Invalid hand tracker model. Keep hand visible.': 'ልክ ያልሆነ የእጅ መከታተያ ሞዴል። እጅዎን በግልጽ ያሳዩ።',
    'Practice sign not trained. Record a template first!': 'የልምምድ ምልክት አልሰለጠነም። መጀመሪያ ሞዴሉን ይቅረጹ!',
    'Adjust the tilt/angle of your hand.': 'የእጅዎን ዝንባሌ/አቅጣጫ ያስተካክሉ።',
    'Excellent form! Keep holding it.': 'በአስተማማኝ ሁኔታ ይዘዋል። ልምምድዎን ይቀጥሉ!',
    'Opening Camera Feed...': 'የካሜራ እይታን በመክፈት ላይ...',
    'Camera Permission Required': 'የካሜራ ፈቃድ ያስፈልጋል',
    'OK': 'እሺ',
    'AI Practice Unavailable': 'የኤአይ ልምምድ አልተገኘም',
    'Failed to load the hand landmarker tracking model or activate the camera.': 'የእጅ ምልክት መከታተያ ሞዴሉን መጫን ወይም ካሜራውን ማንቃት አልተቻለም።',
    'Practice': 'ልምምድ',
    'UNTRAINED': 'ያልሰለጠነ',
    'CORRECT!': 'ትክክል!',
    'ANALYSING...': 'በመተንተን ላይ...',
    'Keep your hand within the frame': 'እጅዎን በካሜራው ክፈፍ ውስጥ ያድርጉ',
    'Stop Practice': 'ልምምዱን አቁም',
    'EVALUATION RESULT': 'የግምገማ ውጤት',
    'Match Confidence': 'የመመሳሰል እርግጠኝነት',
    'INCOMPLETE': 'ያልተሟላ',
    'CORRECT': 'ትክክል',
    'INCORRECT': 'ስህተት',
    'DIAGNOSTIC FEEDBACK': 'የምርመራ አስተያየት',
    'thumb': 'አውራ ጣት',
    'index': 'አመልካች ጣት',
    'middle': 'መካከለኛ ጣት',
    'ring': 'ቀለበት ጣት',
    'pinky': 'ትንሽ ጣት',
    // Profile Screen
    'Full Name': 'ሙሉ ስም',
    'Email Address': 'የኢሜይል አድራሻ',
    'SECURITY': 'ደህንነት',
    'Track your progress': 'ሂደትዎን ይከታተሉ',
    'SIGNS\nLEARNED': 'የተማሩ\nምልክቶች',
    'DAY STREAK': 'ተከታታይ ቀናት',
    'PRACTICED': 'የሰለጠኑበት',
    'Language': 'ቋንቋ',
    'English': 'እንግሊዝኛ',
    'Amharic': 'አማርኛ',
    'coming soon': 'በቅርቡ ይመጣሉ',
    // Dictionary Screen
    'Search signs...': 'ምልክቶችን ይፈልጉ...',
    'All Signs': 'ሁሉም ምልክቶች',
    'Favorites': 'ተወዳጆች',
    // Admin Dashboard Screen
    'Quizzes': 'ፈተናዎች',
    'Add cultural topics like coffee ceremony, holidays': 'እንደ ቡና ሥነ ሥርዓት፣ በዓላት ያሉ ባህላዊ ይርሶችን ይጨምሩ',
    'Cultural Signs': 'ባህላዊ ምልክቶች',
    'Add Ethiopian cultural signs with videos': 'የኢትዮጵያ ባህላዊ ምልክቶችን ከቪዲዮ ጋር ይጨምሩ',
    'User Management': 'የተጠቃሚዎች አስተዳደር',
    'View registered users and their progress': 'የተመዘገቡ ተጠቃሚዎችን and እድገታቸውን ይመልከቱ',
    'Admin login: admin@miliketapp.com\nChanges apply on this device for all users.': 'የአስተዳዳሪ መግቢያ: admin@miliketapp.com\nለውጦች በዚህ መሣሪያ ላይ ላሉት ተጠቃሚዎች ሁሉ ይተገበራሉ።',
    // Admin Categories Screen
    'New Category': 'አዲስ ምድብ',
    'No categories yet.\nTap "New Category" to add a cultural topic.': 'እስካሁን ምንም ምድቦች የሉም። አዲስ ባህላዊ ርዕስ ለመጨመር "አዲስ ምድብ" የሚለውን ይጫኑ።',
    'Add cultural sign': 'ባህላዊ ምልክት ጨምር',
    'Edit': 'አርትዕ',
    'Delete category?': 'ምድብ ሰርዝ?',
    // Admin Category Form Screen
    'New Cultural Category': 'አዲስ ባህላዊ ምድብ',
    'Quick presets': 'ፈጣን ቅንብሮች',
    'Category Name (English)': 'የምድብ ስም (እንግሊዝኛ)',
    'Category Name (Amharic)': 'የምድብ ስም (አማርኛ)',
    'Cultural description': 'ባህላዊ መግለጫ',
    'What Ethiopian culture or tradition does this category cover?': 'ይህ ምድብ የትኛውን የኢትዮጵያ ባህል ወይም ወግ ያካትታል?',
    'Category color': 'የምድብ ቀለም',
    'Save Category': 'ምድቡን አስቀምጥ',
    'Saving...': 'በማስቀመጥ ላይ...',
    'Category updated': 'ምድቡ ተዘምኗል',
    'Category created': 'ምድቡ ተፈጥሯል',
    'Required': 'ግዴታ',
    // Admin Lessons Screen
    'Add Cultural Sign': 'ባህላዊ ምልክት ጨምር',
    'No categories found.': 'ምንም ምድቦች አልተገኙም።',
    'No lessons in this category.': 'በዚህ ምድብ ውስጥ ምንም ትምህርቶች የሉም።',
    'Lesson unlocked': 'ትምህርቱ ተከፍቷል',
    'Lesson locked': 'ትምህርቱ ተቆልፏል',
    'Delete lesson?': 'ትምህርት ይሰረዝ?',
    'Lesson deleted': 'ትምህርቱ ተሰርዟል',
    'No video': 'ቪዲዮ የለም',
    'Lock / Unlock': 'ቆልፍ / ፍታ',
    // Admin Lesson Form Screen
    'Sign updated': 'ምልክቱ ተዘምኗል',
    'Cultural sign added': 'ባህላዊ ምልክት ተጨምሯል',
    'Create a category first before adding signs.': 'ምልክቶችን ከመጨመርዎ በፊት መጀመሪያ ምድብ ይፍጠሩ።',
    'Go back': 'ተመለስ',
    'Example cultural signs': 'ምሳሌ ባህላዊ ምልክቶች',
    'Category': 'ምድብ',
    'Select category': 'ምድብ ይምረጡ',
    'Cultural context (optional)': 'ባህላዊ ይዘት (አማራጭ)',
    'Why is this sign important in Ethiopian culture?': 'ይህ ምልክት በኢትዮጵያ ባህል ውስጥ ለምን አስፈላጊ ሆነ?',
    'Ethiopian Culture home card': 'የኢትዮጵያ ባህል መነሻ ገጽ ካርድ',
    'Upload an image for the home screen Ethiopian Culture card.': 'በባህላዊ ካርድ ላይ የሚሆን ምስል በመነሻ ገጽ ላይ ይጫኑ።',
    'Show on Ethiopian Culture card': 'በባህላዊ ካርድ ላይ አሳይ',
    'Appears on the home screen culture section': 'በመነሻ ገጽ ባህል ክፍል ላይ ይታያል',
    'Change image': 'ምስል ቀይር',
    'Remove': 'አስወግድ',
    'Opening gallery...': 'ማዕከለ-ስዕላትን በመክፈት ላይ...',
    'Pick card image': 'የካርድ ምስል ይምረጡ',
    'Video (drive:ID or Google Drive URL)': 'ቪዲዮ (drive:ID ወይም Google Drive URL)',
    'Upload the sign video to Google Drive and paste the link.': 'የምልክቱን ቪዲዮ በጎግል ድራይቭ ላይ ይጫኑ እና ሊንኩን እዚህ ያያይዙ።',
    'Save Sign': 'ምልክቱን አስቀምጥ',
    'Add a card image to show this sign on the Ethiopian Culture home card.': 'ይህንን ምልክት በኢትዮጵያ ባህል መነሻ ገጽ ካርድ ላይ ለማሳየት የካርድ ምስል ያክሉ።',
  };
}
